<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    function findWithUser($sort = '', $sort_by = '', $q = '', $user_id = 0)
    {
        $where = "WHERE 1=1";
        $order = "ORDER BY ";

        if ($user_id)
            $where.= " AND u.id=:user_id";
        if($q){
            $q = "%$q%";
            $where.= " AND p.name LIKE :q";
        }

        if($sort){
            if($sort=='id')
                $sort=" p.".$sort;
            $order.="$sort $sort_by";
        }
        else{
            $order.="p.id";
        }

        $sql = "SELECT p.id, p.name, p.user_id, p.description, p.price, p.image, u.username, u.email 
                  FROM product p
                  LEFT JOIN fos_user u ON p.user_id = u.id
                  $where
                  $order";

        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        if($user_id)
            $query->bindParam(':user_id',$user_id);
        if($q)
            $query->bindParam(':q',$q);

        $query->execute();

        return $query->fetchAll();
    }
}
